# This is a basic workflow to help you get started with Actions

name: CI devops 2021 EPF
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: main
  pull_request:
jobs:

 build-and-test-app:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Set up JDK 11 
      uses: joschi/setup-jdk@v2
      with: 
       java-version: '11'
    - name: Ajout credentials to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
 build-and-push-docker-image:
  needs: build-and-test-app 
  runs-on: ubuntu-18.04
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN }}  
    - name: Build image and push backend
      uses: docker/build-push-action@v2
      with:
       context: ./simple-api
       tags:
        ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf:simple-api
       push: ${{ github.ref == 'refs/heads/main' }}
    - name: Build image and push database
      uses: docker/build-push-action@v2
      with:
       context: ./database
       tags:
        ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf:database
       push: ${{ github.ref == 'refs/heads/main' }} 
    - name: Build image and push httpd
      uses: docker/build-push-action@v2
      with:
       context: ./httpd
       tags:
        ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-epf:httpd
       push: ${{ github.ref == 'refs/heads/main' }} 
    
    #finally build your app with the latest command
    - name: Build and analyse
      env:
        SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=NicolasCharpenet_Tp2_DevOps
    
